/**
 * Generate TypeScript constants from design tokens
 * Run with: npm run tokens:generate
 *
 * This generator is fully abstract and works with any token structure.
 * Developers only need to edit the tokens.*.json files to add, remove, or modify tokens.
 *
 * Rules:
 * - Mirrors JSON structure exactly (nested objects stay nested)
 * - Each top-level key becomes a named export
 * - All exports use `as const` for type safety
 * - camelCase keys are preserved in TypeScript
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadTokens, type DesignTokens, type TokenValue } from "./load-tokens";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Formats a value for TypeScript output
 */
function formatTsValue(value: TokenValue, indent = 0): string {
  const indentStr = "  ".repeat(indent);

  if (typeof value === "string") {
    // Escape backslashes first, then quotes
    const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `"${escaped}"`;
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (value === null) {
    return "null";
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map(v => formatTsValue(v, indent)).join(", ");
    return `[${items}]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{}";

    const lines: string[] = ["{"];
    entries.forEach(([key, val], index) => {
      const isLast = index === entries.length - 1;
      const formattedValue = formatTsValue(val, indent + 1);
      const comma = isLast ? "" : ",";

      // Check if key needs quotes (contains special chars or starts with number)
      const needsQuotes = /[^a-zA-Z0-9_$]/.test(key) || /^[0-9]/.test(key);
      const keyStr = needsQuotes ? `"${key}"` : key;

      lines.push(`${indentStr}  ${keyStr}: ${formattedValue}${comma}`);
    });
    lines.push(`${indentStr}}`);
    return lines.join("\n");
  }

  return String(value);
}

/**
 * Generates TypeScript constants from design tokens
 */
function generateTypeScript(tokens: DesignTokens): string {
  const lines: string[] = [];

  lines.push(
    "// -----------------------------------------------------------------------------"
  );
  lines.push("// Design Tokens - Generated from tokens.*.json files");
  lines.push("// DO NOT EDIT THIS FILE MANUALLY");
  lines.push(
    "// -----------------------------------------------------------------------------"
  );
  lines.push("");

  // Only generate if tsVars array exists
  if (!tokens.tsVars || tokens.tsVars.length === 0) {
    lines.push("// No TypeScript variables defined.");
    lines.push(
      "// Add a 'tsVars' array to tokens.00-config.json to generate TypeScript exports."
    );
    lines.push("");
    return lines.join("\n");
  }

  // Filter out meta-keys
  const {
    customProperties: _customProperties,
    tsVars: _tsVars,
    ...actualTokens
  } = tokens;

  // Process only tokens listed in tsVars
  for (const varName of tokens.tsVars) {
    const value = actualTokens[varName];
    if (value === undefined) {
      console.warn(
        `Warning: '${varName}' in tsVars not found in design tokens`
      );
      continue;
    }

    const formattedValue = formatTsValue(value);

    // For simple string/number values, export as const directly
    if (
      typeof value === "string" ||
      typeof value === "number" ||
      typeof value === "boolean"
    ) {
      lines.push(`export const ${varName} = ${formattedValue};`);
    } else {
      // For objects/arrays, use 'as const' for type safety
      lines.push(`export const ${varName} = ${formattedValue} as const;`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

// Main execution
try {
  const outputPath = resolve(__dirname, "../foundation/variables.ts");

  const tokens = loadTokens();

  const ts = generateTypeScript(tokens);

  writeFileSync(outputPath, ts, "utf-8");

  console.log("✓ Generated TypeScript constants at foundation/variables.ts");
} catch (error) {
  console.error("Error generating TypeScript:", error);
  process.exit(1);
}
