<?php

/**
 * @file
 * Install, update and uninstall functions for the Media Remote File module.
 */

use Drupal\Core\File\Exception\FileException;
use Drupal\Core\File\FileExists;
use Drupal\Core\File\FileSystemInterface;

/**
 * Implements hook_install().
 */
function media_remote_file_install(): void {
  $source = \Drupal::service('extension.list.module')->getPath('media_remote_file') . '/images/icons';
  $destination = \Drupal::config('media.settings')->get('icon_base_uri');

  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');
  $file_system->prepareDirectory($destination, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);

  foreach (['audio.png', 'video.png'] as $fileName) {
    $icon = $source . DIRECTORY_SEPARATOR . $fileName;
    if (!file_exists($destination . DIRECTORY_SEPARATOR . $fileName)) {
      try {
        $file_system->copy($icon, $destination, FileExists::Error);
      }
      catch (FileException) {
        // Ignore and continue.
      }
    }
  }
}
