// -----------------------------------------------------------------------------
// Design Tokens - Generated from tokens.*.json files
// DO NOT EDIT THIS FILE MANUALLY
// -----------------------------------------------------------------------------

export const NSP = "bsi";

export const breakpoint = {
  sm: "320px",
  md: "576px",
  lg: "992px",
  xl: "1224px"
} as const;
